### ISSUE TITLE
Crash on startup on 1.19.3 on Quilt

### ISSUE THREAD

**Issue by mmmmmabil** [enjarai/shared-resources#10]
wanted to switch over to quilt but after adding my mods the game crashed on startup 
after looking into the log it looked like shared resources was causing it so i made new instances with the other mods and one with only shared resources 
it still crashed while the other instace seemed to work just fine

i am on 
-minecraft 1.19.3
-quilt 0.17.10
-java jdk 17.0.1

 with the mods:
-shared resources 1.3.1
-cloth config 9.0.94

**Comment by mmmmmabil** [comment]
Crashlog 
[crash-2023-01-26_18.10.58-client.txt](https://github.com/enjarai/shared-resources/files/10511871/crash-2023-01-26_18.10.58-client.txt)

**Comment by Kikugie** [comment]
Not all fabric mods may work on quilt, and this one is written for fabric

**Comment by enjarai** [comment]
I'd be down to fix this if possible, but it seems like quilt is loading the 1.19.2 specific components of the mod in addition to the 1.19.3 ones for some reason.

I have no idea why it'd do that, but it might be using a different dependency resolution system for JiJ mods for some reason.

It doesn't seem like something I can fix on my side, so it may be worth contacting quilt devs about this.

**Comment by mmmmmabil** [comment]
@Kikugie i looked at the closed issues to see if smth similar happend before 
and since i saw a closed one that seemed to enable compatibility w quilt i made this one

**Comment by enjarai** [comment]
This might be primarily a fabric mod, but I do try to support quilt where possible.

**Comment by mmmmmabil** [comment]
i mentioned this on the quilt discord 
u seem to have been right with it being a loader issue

someone told me it might work with a beta and the  tried it out after i said i couldn't today

they said that v0.18.1-beta.59 works

**Comment by enjarai** [comment]
Alright, I'll close this then.
