### ISSUE TITLE
Can't create World in 1.19.4 w/ Prism Launcher [Linux Mint]

### ISSUE THREAD

**Issue by EvilsSouls** [enjarai/shared-resources#13]
When I try to create a Singleplayer World it shows the Toast "Failed to copy packs" and sends me back to the Main Menu. When I launch Minecraft it also shows a toast saying "Resource Reload failed", even though it hasn't affected my experience.
![image](https://github.com/enjarai/shared-resources/assets/86242809/08a6b070-d577-4c68-967c-e938674103ff)
![image](https://github.com/enjarai/shared-resources/assets/86242809/1193d251-4470-46ff-bdb1-9b8cfc7669ce)

The mods I'm using:
├──AdaptiveTooltips-1.2.1-fabric-1.19.4.jar
├── advancementinfo-1.19.4-fabric0.76.0-1.3.1.jar
├── animatica-0.5+1.19.jar
├── antighost-1.19.3-fabric0.68.1-1.1.5.jar
├── appleskin-fabric-mc1.19.4-2.4.3.jar
├── BetterBlockOutline-1.5.3-1.19.3.jar
├── bettercommandblockui-0.4.2-1.19.4.jar
├── bettermounthud-1.2.1.jar
├── betterstats-2.6.1+1.19.4.jar
├── borderless-mining-1.1.7+1.19.4.jar
├── capes-1.5.2+1.19.3-fabric.jar
├── CITResewn-1.1.3+1.19.4.jar
├── clientcommands-2.7.11.jar
├── cloth-config-10.0.96-fabric.jar
├── colorful-hex-1.0.0.jar
├── continuity-3.0.0-beta.2+1.19.3.jar
├── DailyDad-fabric-1.19.4-1.5.1.jar
├── DarkKore-0.3.5-1.19.4.jar
├── Debugify-1.19.4+2.2.jar
├── DetailArmorBar-2.6.3+1.19.4-fabric.jar
├── do-a-barrel-roll-2.7.2+1.19.4-fabric.jar
├── dynamic-fps-2.2.0.jar
├── e4mc-3.0.0.jar
├── eating-animation-1.9.3.jar
├── emi-0.7.3+1.19.4.jar
├── entityculling-fabric-1.6.2-mc1.19.4.jar
├── entity_model_features_fabric_1.19.4-0.2.8.jar
├── entity_texture_features_fabric_1.19.4-4.4.0.jar
├── fabric-api-0.80.0+1.19.4.jar
├── fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar
├── fabricskyboxes-0.6.5+mc1.19.4.jar
├── fabrishot-1.9.2.jar
├── fallingleaves-1.15.0+1.19.4.jar
├── farsight-fabric-1.19-3.4.jar
├── fastquit-2.1.0+1.19.3.jar
├── ferritecore-5.2.0-fabric.jar
├── fsb-interop-1.2.0+mc1.19.4-build.31.jar
├── fzmm-mc1.19.4-0.2.2.jar
├── IBEEditor-1.19.4-2.2.2-fabric.jar
├── ImmediatelyFast-1.1.12+1.19.4.jar
├── indium-1.0.15+mc1.19.4.jar
├── inspecio-1.8.0+1.19.4.jar
├── iris-mc1.19.4-1.6.1.jar
├── itemswapper-fabric-0.4.0-mc1.19.4.jar
├── lambdynamiclights-2.3.0+1.19.4.jar
├── language-reload-1.5.5+1.19.4.jar
├── lithium-fabric-mc1.19.4-0.11.1.jar
├── main-menu-credits-1.1.2.jar
├── malilib-fabric-1.19.4-0.15.4.jar
├── memoryleakfix-fabric-1.17+-1.0.0.jar
├── midnightcontrols-1.8.1+1.19.4.jar
├── mixintrace-1.1.1+1.17.jar
├── modelfix-1.10-fabric.jar
├── modmenu-6.2.2.jar
├── morechathistory-1.19.1-1.1.1.jar
├── moreculling-1.19.4-0.17.0.jar
├── NoChatReports-FABRIC-1.19.4-v2.1.1.jar
├── nofade-1.18-2.0.1.jar
├── optigui-2.0.0-beta.3.jar
├── owo-lib-0.10.3+1.19.4.jar
├── physics-mod-2.12.3-mc-1.19.4-fabric.jar
├── pocketwatch-1.1.0+1.19.3.jar
├── puzzle-1.5.0+1.19.4.jar
├── recursive-resources-2.4.1+1.19.4.jar
├── reeses_sodium_options-1.5.0+mc1.19.4-build.72.jar
├── seedmapper-1.5.13.jar
├── shared-resources-1.5.1.jar
├── sodium-extra-0.4.18+mc1.19.4-build.100.jar
├── sodium-fabric-mc1.19.4-0.4.10+build.24.jar
├── starlight-1.1.1+fabric.ae22326.jar
├── symbol-chat-1.19.4-0.7.6.jar
├── toomanybinds-0.3.3+1.19.3.jar
├── tweakeroo-fabric-1.19.4-0.16.0.jar
├── vectorientation-1.0.1a-1.19.3.jar
├── visible-barriers-2.0.1.jar
├── worldedit-mod-7.2.14.jar
├── yet-another-config-lib-fabric-2.5.0+1.19.4.jar
├── yosbr-0.1.1.jar
└── Zoomify-2.9.4.jar

**Comment by EvilsSouls** [comment]
Also, when I first launched the instance with the mod, the popup which lets you configure Shared Resources showed the directory it was going to use as the default .minecraft folder, which I'm not sure is intentional. If I remember correctly, even if I change the directory in the popup menu it isn't changed and I actually have to launch mc and in the config change it.

**Comment by enjarai** [comment]
Please send your log and config file (`.minecraft/config/shared-resources.json`).

**Comment by EvilsSouls** [comment]
Here is the config:[shared-resources.txt](https://github.com/enjarai/shared-resources/files/11472656/shared-resources.txt) (I had to change it to .txt, so that Github would allow me to upload it)

and here is the log:
https://mclo.gs/X0kGh74

**Comment by EvilsSouls** [comment]
Yeah it should be. The weird thing is, is that I selected `~/Minecraft/Shared\ Resources` to be the global directory but it changed it to `/run/user/1000/doc/ff791aa/Shared Resources`. Though when I do look in `~/Minecraft/Shared\ Resources` there are folders and stuff in it. It also seems as if Minecraft creates the world in the default .minecraft folder, but Shared Resources doesn't move it to the universal one.

**Comment by enjarai** [comment]
Are you running prism launcher as a flatpak or other sandboxed application? Those types of installations can't access files or folders on the host system, which could be causing the issue here.

**Comment by EvilsSouls** [comment]
Ah, I have it as a flatpak... Would there be any way how I could fix the problem without reinstalling PrismLauncher?

**Comment by enjarai** [comment]
I don't know how flatpak works, so I couldn't tell you. You'll have to find some way to make external folders accessible to prism. I'm closing this issue, since its not a problem I can fix.

**Comment by RNanB** [comment]
> Ah, I have it as a flatpak... Would there be any way how I could fix the problem without reinstalling PrismLauncher?

Install Flatseal, and for Prism Launcher either turn on All User Files, or add the Shared Resources folder to the list of folders.

**Comment by EvilsSouls** [comment]
> > Ah, I have it as a flatpak... Would there be any way how I could fix the problem without reinstalling PrismLauncher?
> 
> Install Flatseal, and for Prism Launcher either turn on All User Files, or add the Shared Resources folder to the list of folders.

Oh, is Flatseal an app to give Flatpaks the ability to access the file system and modify it? (I just want to know so that I know what it would do)

**Comment by EvilsSouls** [comment]
> > Ah, I have it as a flatpak... Would there be any way how I could fix the problem without reinstalling PrismLauncher?
> 
> Install Flatseal, and for Prism Launcher either turn on All User Files, or add the Shared Resources folder to the list of folders.

How did you do it? I only gave it access to that one specific folder, and now it doesn't even start...
