### ISSUE TITLE
[Feature Request] Add note to worlds saying in which Instance the world was created

### ISSUE THREAD

**Issue by EvilsSouls** [enjarai/shared-resources#14]
It would be nice to have a note on the world which instance it was created in. It could look similar to the warning that shows up on the World's description if you're on a newer/older version, than the one that you were on when you last played the world.

**Comment by User4716** [comment]
Why would you need this?
It seems like a lot of work to just.. see one text that said that you created this world in this modpack.

And you can just put the original modpack name to the world name if you really want it, but we'll see what the owner of this mod decides to do 😉

**Comment by enjarai** [comment]
I won't be adding this, as it is indeed a lot of complexity for something very small.
