### ISSUE TITLE
[Suggestion] Global datapack folder 

### ISSUE THREAD

**Issue by SylisMC** [enjarai/shared-resources#2]
Really looking forward to that full polish you were talking about. only thing you might be missing that would fit perfectly is datapack support

**Comment by enjarai** [comment]
Datapacks are world-based, so they're included with your global saves. If you're looking for mods that make datapacks shared between worlds, there are enough other mods that do that.

**Comment by dopadream** [comment]
can you please reconsider this? it would be far more convenient to have everything in one place (which is very possible thanks to what you've created here). the other mods out there for saved datapacks do not save across instances

**Comment by enjarai** [comment]
That definitely makes sense. I generally want to keep this mod solely focused on sharing data between instances, but this might be a reasonable exception to make, as it opens up otherwise impossible functionality. I'll put it on the todo list. 👍

**Comment by dopadream** [comment]
wow i did not think that would actually work, you're the best lol, even if it doesnt get added thank you for taking it into consideration

**Comment by enjarai** [comment]
1.5.0 implements global datapacks support. When the option is not enabled, it'll still provide a local datapacks folder which is shared between all worlds. Be sure to let me know if you encounter any issues. :)
