### ISSUE TITLE
⛔[Crash] Incompatible with Colormatic

### ISSUE THREAD

**Issue by User4716** [enjarai/shared-resources#20]
If you install SharedResources v1.6.0 and Colormatic https://modrinth.com/mod/colormatic
The game crashes when you boot it (Also I have QFAPI and Cloth Config as requirements)

Here's the [crash-report.txt](https://github.com/enjarai/shared-resources/files/12320561/crash-report.txt)

And here is the [latest.log](https://github.com/enjarai/shared-resources/files/12320566/latest.log)

**Comment by enjarai** [comment]
Seems like you're using a version of colormatic that doesn't work on 1.20. This has nothing to do with this mod, even though the crash report thinks it does for some reason.
