### ISSUE TITLE
Support for Continue

### ISSUE THREAD

**Issue by zndrmn** [enjarai/shared-resources#22]
[https://modrinth.com/mod/continue](https://modrinth.com/mod/continue)

This only happens when trying to enter a singleplayer world inside the global folder

![2023-08-11_19 58 42](https://github.com/enjarai/shared-resources/assets/77690119/53725fd4-ff21-4203-8674-16f15e12f15f)

**Comment by enjarai** [comment]
This is an issue with Continue, please report it to it's author instead.
