### ISSUE TITLE
Update to 1.20.2

### ISSUE THREAD

**Issue by ASOwnerYT** [enjarai/shared-resources#27]
Currently the mod doesn't seem to work on 1.20.2. After testing it with the Simply Optimised modpack (1.20.2-1.0.1), the game crashed on launch with the following error: 

`[Render thread/ERROR]: Failed to parse allowed_symlinks.txt, disallowing all symbolic links`

Full log: https://mclo.gs/YVKVOVh

**Comment by enjarai** [comment]
1.6.1 is currently publishing with 1.20.2 support.
