### ISSUE TITLE
Crash on startup (MC 1.16.5)

### ISSUE THREAD

**Issue by Indexception** [enjarai/shared-resources#29]
I am having a crash whenever I try to launch Minecraft (1.16.5). Looking at the log it looks like the mod requires Java 17, but Minecraft 1.16.5 is running on Java 8. On mod's page it says there is support for 1.16.5, maybe I am doing something wrong.

Details:
Java 1.8.0_372 (Azul Zulu)
Prism Launcher 7.2
Minecraft 1.16.5
Fabric 0.14.23

Installed Mods:
Cloth Config 4.17.101
Fabric API 0.42.0+1.16
Mod Menu 1.16.23
Shared Resources 1.6.1

Log:
Prism Launcher version: 7.2 (official)

Launched instance in online mode

authserver.mojang.com resolves to:
    [18.244.146.10, 18.244.146.37, 18.244.146.71, 18.244.146.76]

session.minecraft.net resolves to:
    [13.107.246.44, 13.107.213.44]

textures.minecraft.net resolves to:
    [13.107.213.44, 13.107.246.44]

api.mojang.com resolves to:
    [13.107.213.44, 13.107.246.44]

Minecraft folder is:
C:/Users/index/Documents/Games/Minecraft/.multimc/instances/test-1.16.5/.minecraft

Java path is:
C:/Program Files/Zulu/zulu-8/bin/javaw.exe

Java is version 1.8.0_372, using 64 (amd64) architecture, from Azul Systems, Inc..

Main Class:
  net.fabricmc.loader.impl.launch.knot.KnotClient

Native path:
  C:/Users/index/Documents/Games/Minecraft/.multimc/instances/test-1.16.5/natives

Traits:
traits FirstThreadOnMacOS
traits XR:Initial

Libraries:
  C:/Users/index/Apps/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2.jar
  C:/Users/index/Apps/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2.jar
  C:/Users/index/Apps/PrismLauncher/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2.jar
  C:/Users/index/Apps/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2.jar
  C:/Users/index/Apps/PrismLauncher/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2.jar
  C:/Users/index/Apps/PrismLauncher/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2.jar
  C:/Users/index/Apps/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2.jar
  C:/Users/index/Apps/PrismLauncher/libraries/com/mojang/patchy/1.3.9/patchy-1.3.9.jar
  C:/Users/index/Apps/PrismLauncher/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar
  C:/Users/index/Apps/PrismLauncher/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar
  C:/Users/index/Apps/PrismLauncher/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar
  C:/Users/index/Apps/PrismLauncher/libraries/com/ibm/icu/icu4j/66.1/icu4j-66.1.jar
  C:/Users/index/Apps/PrismLauncher/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar
  C:/Users/index/Apps/PrismLauncher/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar
  C:/Users/index/Apps/PrismLauncher/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar
  C:/Users/index/Apps/PrismLauncher/libraries/com/google/guava/guava/21.0/guava-21.0.jar
  C:/Users/index/Apps/PrismLauncher/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar
  C:/Users/index/Apps/PrismLauncher/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar
  C:/Users/index/Apps/PrismLauncher/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar
  C:/Users/index/Apps/PrismLauncher/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar
  C:/Users/index/Apps/PrismLauncher/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar
  C:/Users/index/Apps/PrismLauncher/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar
  C:/Users/index/Apps/PrismLauncher/libraries/com/mojang/authlib/2.1.28/authlib-2.1.28.jar
  C:/Users/index/Apps/PrismLauncher/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar
  C:/Users/index/Apps/PrismLauncher/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar
  C:/Users/index/Apps/PrismLauncher/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
  C:/Users/index/Apps/PrismLauncher/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar
  C:/Users/index/Apps/PrismLauncher/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar
  C:/Users/index/Apps/PrismLauncher/libraries/org/apache/logging/log4j/log4j-api/2.17.1/log4j-api-2.17.1.jar
  C:/Users/index/Apps/PrismLauncher/libraries/org/apache/logging/log4j/log4j-core/2.17.1/log4j-core-2.17.1.jar
  C:/Users/index/Apps/PrismLauncher/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar
  C:/Users/index/Apps/PrismLauncher/libraries/net/fabricmc/intermediary/1.16.5/intermediary-1.16.5.jar
  C:/Users/index/Apps/PrismLauncher/libraries/net/fabricmc/tiny-mappings-parser/0.3.0+build.17/tiny-mappings-parser-0.3.0+build.17.jar
  C:/Users/index/Apps/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar
  C:/Users/index/Apps/PrismLauncher/libraries/net/fabricmc/tiny-remapper/0.8.2/tiny-remapper-0.8.2.jar
  C:/Users/index/Apps/PrismLauncher/libraries/net/fabricmc/access-widener/2.1.0/access-widener-2.1.0.jar
  C:/Users/index/Apps/PrismLauncher/libraries/org/ow2/asm/asm/9.6/asm-9.6.jar
  C:/Users/index/Apps/PrismLauncher/libraries/org/ow2/asm/asm-analysis/9.6/asm-analysis-9.6.jar
  C:/Users/index/Apps/PrismLauncher/libraries/org/ow2/asm/asm-commons/9.6/asm-commons-9.6.jar
  C:/Users/index/Apps/PrismLauncher/libraries/org/ow2/asm/asm-tree/9.6/asm-tree-9.6.jar
  C:/Users/index/Apps/PrismLauncher/libraries/org/ow2/asm/asm-util/9.6/asm-util-9.6.jar
  C:/Users/index/Apps/PrismLauncher/libraries/net/fabricmc/fabric-loader/0.14.23/fabric-loader-0.14.23.jar
  C:/Users/index/Apps/PrismLauncher/libraries/com/mojang/minecraft/1.16.5/minecraft-1.16.5-client.jar

Native libraries:
  C:/Users/index/Apps/PrismLauncher/libraries/org/lwjgl/lwjgl-glfw/3.2.2/lwjgl-glfw-3.2.2-natives-windows.jar
  C:/Users/index/Apps/PrismLauncher/libraries/org/lwjgl/lwjgl-jemalloc/3.2.2/lwjgl-jemalloc-3.2.2-natives-windows.jar
  C:/Users/index/Apps/PrismLauncher/libraries/org/lwjgl/lwjgl-openal/3.2.2/lwjgl-openal-3.2.2-natives-windows.jar
  C:/Users/index/Apps/PrismLauncher/libraries/org/lwjgl/lwjgl-opengl/3.2.2/lwjgl-opengl-3.2.2-natives-windows.jar
  C:/Users/index/Apps/PrismLauncher/libraries/org/lwjgl/lwjgl-stb/3.2.2/lwjgl-stb-3.2.2-natives-windows.jar
  C:/Users/index/Apps/PrismLauncher/libraries/org/lwjgl/lwjgl/3.2.2/lwjgl-3.2.2-natives-windows.jar
  C:/Users/index/Apps/PrismLauncher/libraries/org/lwjgl/lwjgl-tinyfd/3.2.2/lwjgl-tinyfd-3.2.2-natives-windows.jar
  C:/Users/index/Apps/PrismLauncher/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3-natives-windows.jar

Mods:
  [✔] cloth-config-4.17.101-fabric
  [✔] fabric-api-0.42.0+1.16
  [✔] modmenu-1.16.23
  [✔] shared-resources-1.6.1

Params:
  --username  --version 1.16.5 --gameDir C:/Users/index/Documents/Games/Minecraft/.multimc/instances/test-1.16.5/.minecraft --assetsDir C:/Users/index/Apps/PrismLauncher/assets --assetIndex 1.16 --uuid  --accessToken  --userType  --versionType release

Window size: max (if available)

Launcher: standard

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms512m, -Xmx14336m, -Duser.language=en]

Minecraft process ID: 13264

ScriptEngineManager providers.next(): javax.script.ScriptEngineFactory: Provider jdk.nashorn.api.scripting.NashornScriptEngineFactory not found
[17:13:10] [main/INFO]: Loading Minecraft 1.16.5 with Fabric Loader 0.14.23
[17:13:10] [main/INFO]: Fabric is preparing JARs on first launch, this may take a few seconds...
[17:13:10] [main/INFO]: Loading 55 mods:
	- cloth-config2 4.17.101
	   \-- cloth-basic-math 0.6.1
	- fabric 0.42.0+1.16
	   |-- fabric-api-base 0.4.0+3cc0f0907d
	   |-- fabric-api-lookup-api-v1 1.3.1+3cc0f0907d
	   |-- fabric-biome-api-v1 3.1.13+3cc0f0907d
	   |-- fabric-blockrenderlayer-v1 1.1.6+3cc0f0907d
	   |-- fabric-command-api-v1 1.1.3+3cc0f0907d
	   |-- fabric-commands-v0 0.2.3+3cc0f0907d
	   |-- fabric-containers-v0 0.1.12+3cc0f0907d
	   |-- fabric-content-registries-v0 0.2.5+3cc0f0907d
	   |-- fabric-crash-report-info-v1 0.1.4+3cc0f0907d
	   |-- fabric-dimensions-v1 2.0.8+3cc0f0907d
	   |-- fabric-entity-events-v1 1.2.4+3cc0f0907d
	   |-- fabric-events-interaction-v0 0.4.5+3cc0f0907d
	   |-- fabric-events-lifecycle-v0 0.2.2+3cc0f0907d
	   |-- fabric-game-rule-api-v1 1.0.7+3cc0f0907d
	   |-- fabric-item-api-v1 1.2.2+3cc0f0907d
	   |-- fabric-item-groups-v0 0.3.1+3cc0f0907d
	   |-- fabric-key-binding-api-v1 1.0.5+3cc0f0907d
	   |-- fabric-keybindings-v0 0.2.2+3cc0f0907d
	   |-- fabric-lifecycle-events-v1 1.2.2+3cc0f0907d
	   |-- fabric-loot-tables-v1 1.0.3+3cc0f0907d
	   |-- fabric-mining-levels-v0 0.1.4+3cc0f0907d
	   |-- fabric-models-v0 0.3.1+3cc0f0907d
	   |-- fabric-networking-api-v1 1.0.5+3cc0f0907d
	   |-- fabric-networking-blockentity-v0 0.2.9+3cc0f0907d
	   |-- fabric-networking-v0 0.3.3+3cc0f0907d
	   |-- fabric-object-builder-api-v1 1.9.6+3cc0f0907d
	   |-- fabric-object-builders-v0 0.7.3+3cc0f0907d
	   |-- fabric-particles-v1 0.2.5+3cc0f0907d
	   |-- fabric-registry-sync-v0 0.7.6+3cc0f0907d
	   |-- fabric-renderer-api-v1 0.4.5+3cc0f0907d
	   |-- fabric-renderer-indigo 0.4.5+3cc0f0907d
	   |-- fabric-renderer-registries-v1 2.3.1+3cc0f0907d
	   |-- fabric-rendering-data-attachment-v1 0.1.6+3cc0f0907d
	   |-- fabric-rendering-fluids-v1 0.1.15+3cc0f0907d
	   |-- fabric-rendering-v0 1.1.3+3cc0f0907d
	   |-- fabric-rendering-v1 1.6.1+3cc0f0907d
	   |-- fabric-resource-loader-v0 0.4.8+3cc0f0907d
	   |-- fabric-screen-api-v1 1.0.1+3cc0f0907d
	   |-- fabric-screen-handler-api-v1 1.1.6+3cc0f0907d
	   |-- fabric-structure-api-v1 1.1.12+3cc0f0907d
	   |-- fabric-tag-extensions-v0 1.1.2+3cc0f0907d
	   |-- fabric-textures-v0 1.0.7+3cc0f0907d
	   |-- fabric-tool-attribute-api-v1 1.2.8+3cc0f0907d
	   \-- fabric-transfer-api-v1 1.5.0+3cc0f0907d
	- fabricloader 0.14.23
	- java 8
	- minecraft 1.16.5
	- modmenu 1.16.23
	- shared-resources 1.6.1
	   |-- com_github_llamalad7_mixinextras 0.1.1
	   |-- shared-resources-api 1.6.1
	   \-- shared-resources-mc16 1.6.1
[17:13:11] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/index/Apps/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
Exception caught from launcher
java.lang.RuntimeException: Error creating Mixin config shared-resources.mixins.json for mod shared-resources
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:95)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config shared-resources.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:93)
	... 6 more
Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_17 could not be set. Level is not supported by the active JRE or ASM version (Java 1.8, ASM 9.6 (ASM10_EXPERIMENTAL))
	at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1570)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:557)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:502)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:430)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1293)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 9 more
Exiting with ERROR
Process exited with code 2.
Clipboard copy at: 25 Oct 2023 17:14:01 +0200
Clipboard copy at: 25 Oct 2023 17:23:05 +0200
Clipboard copy at: 25 Oct 2023 17:28:11 +0200

**Comment by enjarai** [comment]
Fixed in 1.7.0.
