### ISSUE TITLE
[Feature request] Figura avatars sync

### ISSUE THREAD

**Issue by PencilVoid** [enjarai/shared-resources#32]
The mod [Figura](https://modrinth.com/mod/figura) uses a folder in .minecraft named "figura" for storing avatars and related assets. It would be useful if this folder could be shared between instances.

**Comment by OracleHisty** [comment]
I second this. I do avatar creation across profiles and I hate backing them up over and over across them when I show my friends in seperate modpacks.

**Comment by enjarai** [comment]
Added in the latest version.
