### ISSUE TITLE
❓[Question] Any plans for Forge support?

### ISSUE THREAD

**Issue by User4716** [enjarai/shared-resources#38]
I recently created a Forge modpack and the first and most noticeable difference from all of my Fabric profiles is the fact, that I don't have Shared resources on there. So if you have any plans on making a Forge version of this mod, it would be great 🙏

**Comment by enjarai** [comment]
I currently have no plans to make a Forge port. I understand how it would be great to have, but it'd require some significant rewriting that I'm not willing to do.

There is however a 1.20.4 update coming soon™, I haven't completely abandoned this mod lmao.
