### ISSUE TITLE
World saves corrupting

### ISSUE THREAD

**Issue by PencilVoid** [enjarai/shared-resources#39]
A weird issue I've observed on the latest version. In 1.20.2, any save that wasn't created in 1.20.2 doesn't appear in the world list, and those that do seem to be corrupted. The world icon is gone, and loading the world causes certain chunks to be deleted and regenerated, but I'd have to test this further.

Of the 3 worlds that did show in the list, one of them had this folder structure with certain folders missing:
![image](https://github.com/enjarai/shared-resources/assets/83508866/c8e3ff13-bb35-4271-866f-419b2c655b86)

[Game log](https://mclo.gs/D62q7UJ)

Additionally, resource packs are immediately reloaded again after they are initially loaded by the game launching, but that seems to be a separate issue.

**Comment by MintLightning** [comment]
I'm having the same issue. It erased all the data from all my worlds but somehow left the folder structure in tact. I'm really not sure what happened, but several hundred hours of work are now gone.

I guess that's what I get for not saving backups :/

**Comment by PencilVoid** [comment]
From further testing I've also noticed that new worlds I create disappear when I close the game.


> I guess that's what I get for not saving backups :/

I would be toast right now if it weren't for [Rclone](https://rclone.org/). It makes copying data to another drive very convenient if you write a batch script for it.

**Comment by PovarRavop** [comment]
If I had not seen your issue, then all my worlds would have been deleted. Thanks for the warning!

> A weird issue I've observed on the latest version. In 1.20.2, any save that wasn't created in 1.20.2 doesn't appear in the world list, and those that do seem to be corrupted. The world icon is gone, and loading the world causes certain chunks to be deleted and regenerated, but I'd have to test this further.
> 
> Of the 3 worlds that did show in the list, one of them had this folder structure with certain folders missing: ![image](https://private-user-images.githubusercontent.com/83508866/321286545-c8e3ff13-bb35-4271-866f-419b2c655b86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI3Nzc4MzYsIm5iZiI6MTcxMjc3NzUzNiwicGF0aCI6Ii84MzUwODg2Ni8zMjEyODY1NDUtYzhlM2ZmMTMtYmIzNS00MjcxLTg2NmYtNDE5YjJjNjU1Yjg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEwVDE5MzIxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxYjhjMjA1MzU2NmNkN2QwOTc5YzA0NDRjOGVmYTMwYTQ4YjU0ZjZkNGVjYjNjMWUzNjg4OGViZWM5NTUyNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Xn350uE57nFCNf9GXil4KAZfg8yZp6Hqg7ddprff7Dw)
> 
> [Game log](https://mclo.gs/D62q7UJ)
> 
> Additionally, resource packs are immediately reloaded again after they are initially loaded by the game launching, but that seems to be a separate issue.

If I had not seen your issue, then all my worlds would have been deleted. Thanks for the warning!

**Comment by enjarai** [comment]
I've diagnosed and fixed the issue with @MintLightning in discord. Turns out an old mixin was touching places it shouldn't in newer versions.

The problem has been fixed as of 1.8.1. Affected versions have been deleted from mod publishing websites just to be safe. I'm very sorry this happened, and hope the damage was minimal.
