### ISSUE TITLE
Identifiers use incorrect namespace in 1.21

### ISSUE THREAD

**Issue by Johni0702** [enjarai/shared-resources#47]
It seems that in 1.21, [all the builtin resources provided by shared-resources itself](https://github.com/enjarai/shared-resources/blob/316936eda231cdd15fc0e880d22d2b095336b588/src/main/java/nl/enjarai/shared_resources/registry/GameResources.java#L105-L126) now use the `minecraft` namespace, whereas in previous versions they all used the `shared-resources` namespace.
As a result, mods which previously consulted shared-resources will no longer actually receive the correct folder, at least until updated to account for this change. The [DefaultGameResources](https://github.com/enjarai/shared-resources/blob/316936eda231cdd15fc0e880d22d2b095336b588/shared-resources-api/src/main/java/nl/enjarai/shared_resources/api/DefaultGameResources.java) API class also still uses the old namespace, which leads me to suspect that this change was probably not intentional?

The relevant code is this:
https://github.com/enjarai/shared-resources/blob/316936eda231cdd15fc0e880d22d2b095336b588/src/main/java/nl/enjarai/shared_resources/SharedResources.java#L16-L22
Note how the 1.21 variant is missing the `MODID`, so `Identifier.of` instead falls back to using the vanilla namespace.

**Comment by enjarai** [comment]
Ah, that is indeed a bug, thanks for letting me know. I'll push a fix.
