### ISSUE TITLE
How to completely delete Shared Resources

### ISSUE THREAD

**Issue by zed1ker** [enjarai/shared-resources#48]
I deleted the mod, but everything remains. If you delete it when you start the game, it appears again

how to delete it completely

**Comment by enjarai** [comment]
The mod is definitely not supposed to do that. You might be using a custom launcher that keeps redownloading it?

**Comment by zed1ker** [comment]
![image](https://github.com/user-attachments/assets/00966aa1-a2e9-4c87-a4d7-e26c63b34095)
I have a prism launcher and it doesn't seem to do that

**Comment by enjarai** [comment]
Ah, that is the API module. Some other mods include it in their jar so they can use it reliably. Like it says, it has no functionality by itself, so its safe to ignore.

**Comment by enjarai** [comment]
It will hide itself if you hide library mods iirc, or you can blacklist it in the modmenu config. You could also find out what mod is using it by checking your log file and delete that.
