### ISSUE TITLE
[Suggestion] Make "Open Pack Folder" button in settings open shared resources resourcepack folder instead of .minecraft/resourcepacks

### ISSUE THREAD

**Issue by mvilk** [enjarai/shared-resources#5]
Make "Open Pack Folder" button in settings open shared resources resourcepack folder instead of .minecraft/resourcepacks.
Some people might not like this change, so would be great to have config option for which folder this button opens.

**Comment by enjarai** [comment]
Added in 1.2.3, without a config option. I might implement a better solution later, but for now it makes sense to me to have it this way.
